### ISSUE TITLE
Setting of output folder

### ISSUE THREAD

**Issue by veitveit** [statOmics/MSqRob#10]
When starting the shiny app in RStudio on Linux, the file browser to set the output location does not open. One can see the message
_Choose a directory [/usr/lib/R/library/MSqRob/App-MSqRob]: _
in the terminal. 

The program can be used when specifying the location in the terminal.

**Comment by ludgergoeminne** [comment]
This was a temporary solution for Linux in the previous versions but should now be fixed in the newest version of MSqRob (0.6.4) with a folder selection window now also available on Linux (via zenity). Can you please confirm that you get a folder selection window on Linux?

**Comment by ludgergoeminne** [comment]
The problem seems to be solved. I will close this issue for now.
