### ISSUE TITLE
files names missing from DESCRIPTION

### ISSUE THREAD

**Issue by duongch4** [statOmics/MSqRob#15]
Hi,

I am trying to install MSqRob package from github, and I think you have not added these 2 files in the \R folder to the DESCRIPTION file, so the 'Collate' error happens. Would you mind check that out?

**Comment by ludgergoeminne** [comment]
Dear duongch4

Thank you for the remark. These were test files for a future version that I had already uploaded by accident. The files have been removed. It should now be possible to install MSqRob again. Please let me know if you would run into further issues!

Cheers

Ludger

**Comment by ludgergoeminne** [comment]
The problem seems to be solved. I will close this issue for now.
