### ISSUE TITLE
ade

### ISSUE THREAD

**Issue by adepage** [statOmics/MSqRob#2]
We have an issue to install MSqRob see below the error message :
> devtools::install_github("statOmics/MSqRob")
Downloading GitHub repo statOmics/MSqRob@master
from URL https://api.github.com/repos/statOmics/MSqRob/zipball/master
Installing MSqRob
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL "C:/Users/apage/AppData/Local/Temp/RtmpuiI5Fh/devtools11d412d32e8a/statOmics-MSqRob-5131df1"  \
  --library="C:/Users/apage/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'MSqRob' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'Rcpp'
Error : package 'lme4' could not be loaded
ERROR: lazy loading failed for package 'MSqRob'
* removing 'C:/Users/apage/Documents/R/win-library/3.3/MSqRob'
Error: Command failed (1)
> 
Thank in advance for helping us

**Comment by ludgergoeminne** [comment]
Dear adepage

This is again the issue with install_github (hadley/devtools#1298) not being able to install dependencies of dependencies. I have now also added "Rcpp" in my DESCRIPTION file, so try to install MSqRob again via:

devtools::install_github("statOmics/MSqRob")
library(MSqRob)

If there would other packages missing as well, you can solve this by entering:

install.packages("Rcpp")

(replace "Rcpp" by the name of the package, also with quotes).

If this would be the case, can you let me know which packages were still missing on your system so I can also add them? Thanks in advance!

If this is not the solution to your problem, there could be other issues with the package Rccp as well (see for example http://stackoverflow.com/questions/16758129/error-in-loadnamespacename-there-is-no-package-called-rcpp). But if this would be the case, I would need to look further into it.

Please for now just try to reinstall MSqRob and other potential missing packages and let me know if this fixed your problem!

**Comment by ludgergoeminne** [comment]
The problem seems to be solved. I will close this issue for now.
