### ISSUE TITLE
ade

### ISSUE THREAD

**Issue by adepage** [statOmics/MSqRob#3]
Thank you for your help We have an other issue:
> shiny::runApp(system.file('App-MSqRob', package = 'MSqRob'))
Loading required package: shiny

Listening on http://127.0.0.1:3469

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show

ERROR: [on_request_read] connection reset by peer
Loading required package: Matrix
Warning: Error in : package ‘BiocGenerics’ required by ‘MSnbase’ could not be found
Stack trace (innermost first):
    41: .getRequiredPackages2
    40: library
     1: shiny::runApp
Error : package ‘BiocGenerics’ required by ‘MSnbase’ could not be found

Thank you again

**Comment by ludgergoeminne** [comment]
Dear adepage

I have added BiocGenerics to the list of dependencies.
It should work now if you try to reinstall MSqRob.

Cheers

Ludger

**Comment by ludgergoeminne** [comment]
The problem seems to be solved. I will close this issue for now.
