### ISSUE TITLE
Ade Biocgenerics package

### ISSUE THREAD

**Issue by adepage** [statOmics/MSqRob#4]
We have install MSqRob but Biocgenerics is not installed:
> install.packages("Biocgenerics")
Installing package into ‘C:/Users/apage/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘Biocgenerics’ is not available (for R version 3.3.3)

We have installed R version 3.3.3, should we go back to an older version and which one?

**Comment by ludgergoeminne** [comment]
Dear adepage

This is because BiocGenerics is a Bioconductor package.
It should be installed like this:

source("https://bioconductor.org/biocLite.R")
biocLite("BiocGenerics")

But this should now no longer be necessary because I have added BiocGenerics to our list of dependencies.

Cheers

Ludger

**Comment by ludgergoeminne** [comment]
The problem seems to be solved. I will close this issue for now.
