### ISSUE TITLE
saves_MSqRob side effects in saves_MSqRob

### ISSUE THREAD

**Issue by wolski** [statOmics/MSqRob#50]
It seems that the saves_MSqRob changes the working directory:

```
> getwd()
[1] "D:/Dropbox/DataAnalysis/p2244_Adult_childrenAnalysis/RAnalysisAdultsChildren"
> #If you chose to save the model, save it
> if(isTRUE(save_model)){
+   result_files <- list()
+   result_files$proteins <- proteins
+   result_files$models <- models
+   result_files$levelOptions <- rownames(L)
+   result_files$fixed <- fixed
+   result_files$random <- random
+   saves_MSqRob(result_files, file=file.path(export_folder,"model.RDatas"), overwrite=TRUE)
+ }
 Show Traceback
 
 Rerun with Debug
 Error in file(tarfile, "wb") : 
  (converted from warning) cannot open file './tmp/model.RDatas': No such file or directory 
> getwd()
[1] "C:/Users/wolski/AppData/Local/Temp/RtmpwPeqxy/saves.dir-1a843c3e5832"
```

**Comment by ludgergoeminne** [comment]
Hi Witold

It seems that your attempt to save the model failed exactly at the wrong line of code.
saves_MSqRob creates a temporary directory, sets this as working directory, compresses your data and then resets the working directory. Apparently in your case something went wrong with saving the data, which caused the resetting of the working directory to fail.

I have added a tryCatch statement that makes sure that if the saving would fail, the working directory would be restored. You can reinstall MSqRob using:

`devtools::install_github("statOmics/MSqRob@MSqRob0.7.5")
library(MSqRob)`

If you can send me a reproducible example of why your saving failed, I could also look into that.

**Comment by wolski** [comment]
Thanks
