### ISSUE TITLE
License and LICENSE file is missing

### ISSUE THREAD

**Issue by bgruening** [statOmics/MSqRob#54]
Hi,

it would be nice if you could mention a license in a LICENSE file.

Thanks!

**Comment by ludgergoeminne** [comment]
Dear Björn

I indeed didn't add a license yet, I will discuss this with my promotors and I will add a license as soon as possible. We will most likely go for a permissive license, genre Apache 2.0 or MIT, but I will keep you updated. For me personally, anyone can use MSqRob as long as they give proper credit (e.g. citation).
Do note however that certain dependencies of MSqRob, e.g. lme4, are published under the GPL license. This means that if you would want to use MSqRob for commercial applications, you would need to strip out and replace all of its GPL dependencies.

Cheers

Ludger

**Comment by ludgergoeminne** [comment]
Dear Björn

In the end, we have decided to license MSqRob under the GPL 2.0 or higher.
I have added the corresponding LICENSE file.

Cheers

Ludger

**Comment by bgruening** [comment]
Thanks a lot!

**Comment by bgruening** [comment]
I added a conda recipe here: https://bioconda.github.io/recipes/r-msqrob/README.html

**Comment by ludgergoeminne** [comment]
Ok, thanks!
