### ISSUE TITLE
Potential bug in variable shrinkage code?

### ISSUE THREAD

**Issue by rohan-shah** [statOmics/MSqRob#65]
Hi, I'm seeing some behaviour I don't understand regarding the shrinkage of fixed effects, and I think this could plausibly be a bug. 

As an example, I've been running `MSqRobData/extdata/CPTAC/analysis_CPTAC.html` (my version is dated 2017-03-06), and debugging the fit.model function, which in that script is 
```
models <- fit.model(protdata=proteins, response="quant_value", fixed=fixed, random=random)
```

There is a particular couple of lines in `.createParsedFormula` that reads:
```
if (n >= length(fixed.names)) {
    x[, paste0("ridgeGroup.", i)] <- factor(rep(fixed.names, 
        length = n), levels = fixed.names)
} else {
    x[, paste0("ridgeGroup.", i)] <- factor(rep(NA, length = n), 
        levels = fixed.names)
}
```
If I examine `x` after those lines, I see the following:
```
Browse[2]> head(x)
   quant_value                   Sequence        PEP      run condition              lab        ridgeGroup.1
2     15.89625 SequenceAAAAGAGGAGDSGDAVTK 1.1843e-05 runX6A_2        6A  LTQ-Orbitrap_86         condition6B
4     15.74427 SequenceAAAAGAGGAGDSGDAVTK 1.1843e-05 runX6A_4        6A LTQ-OrbitrapO_65         condition6C
5     16.11690 SequenceAAAAGAGGAGDSGDAVTK 1.1843e-05 runX6A_5        6A LTQ-OrbitrapO_65         condition6D
6     16.26360 SequenceAAAAGAGGAGDSGDAVTK 1.1843e-05 runX6A_6        6A LTQ-OrbitrapO_65         condition6E
9     16.40301 SequenceAAAAGAGGAGDSGDAVTK 1.1843e-05 runX6A_9        6A LTQ-OrbitrapW_56 labLTQ-OrbitrapO_65
14    15.60504 SequenceAAAAGAGGAGDSGDAVTK 1.1843e-05 runX6B_5        6B LTQ-OrbitrapO_65 labLTQ-OrbitrapW_56
Browse[2]> str(fixed.names)
 chr [1:6] "condition6B" "condition6C" "condition6D" "condition6E" "labLTQ-OrbitrapO_65" "labLTQ-OrbitrapW_56"
```
Note that the new column ridgeGroup.1 seems to bear no relation to the other columns. Is this as intended? It seems extremely weird.

**Comment by ludgergoeminne** [comment]
Dear Rohan

This is not a bug, it is just a programming trick to force lme4 into fitting a ridge regression model.
Indeed, in ridge regression, all effects get the same shrinkage penalty,
while random effects in lme4 get a separate shrinkage penalty for each random effect.

We want to make use of the random effects in the lme4 framework to do ridge regression on our fixed effects. Therefore, we create a ridgeGroup, which contains the levels of all fixed effects in the model (optionally, MSqRob allows specify multiple ridgeGroups, whereby all fixed effects within each ridgeGroup will receive the same shrinkage penalty). These ridgeGroups are only needed to create the parsed formula object, however, they are not included in the final model matrix. The model matrix is indeed based on the true fixed effects:

MM <- model.matrix(formula_fix, data=x)

This model matrix is, after QR-decomposition, inserted into the model matrix of the parsed formula object.

See:

num_indices <- as.list(which(names(parsedFormula$reTrms$cnms) %in% ridgeGroups))
    Zt_indices <- unlist(lapply(as.list(num_indices), function(z){return((parsedFormula$reTrms$Gp+1)[z]:parsedFormula$reTrms$Gp[z+1])}))

and:

Zt[Zt_indices,] <- Matrix::t(Q_fix[,-unshr_pos,drop=FALSE])

I realize that the code looks somewhat messy, my apologies for that.
