### ISSUE TITLE
BiocInstaller isn't available anymore

### ISSUE THREAD

**Issue by lgatto** [statOmics/MSqRob#72]
PR #71 removes `BiocInstaller` from the `Imports`, as it isn't available any more and stops `MSqRob` installing on R 3.6.x. Please let me know asap when the PR is merged, as I need it to send the summer school students the installation instructions.

**Comment by ludgergoeminne** [comment]
Thanks, Laurent!
I have merged the PR.
Please let me know if there would be any further issues.
