### ISSUE TITLE
update 2017 reference in README

### ISSUE THREAD

**Issue by pwilmart** [statOmics/MSqRob#76]
Hi,
You might want to update the 2017 reference to the actual publication at the end of the README file:

Goeminne, L.J., Gevaert, K. and Clement, L., 2018. Experimental design and data-analysis in label-free quantitative LC/MS proteomics: A tutorial with MSqRob. Journal of proteomics, 171, pp.23-36.

Cheers,
Phil

**Comment by ludgergoeminne** [comment]
Hi Phil

Thanks for pointing this out!
I have updated the reference accordingly.

Cheers

Ludger
