### ISSUE TITLE
How to show saved data in MSQRob Shiny App

### ISSUE THREAD

**Issue by andrewjmc** [statOmics/MSqRob#78]
Hello,

Many thanks for such a useful tool. I might have missed it in the vignette, but when you reload saved data (loads_MSqRob) how do you then display it in the Shiny App?

Thanks,

Andrew

**Comment by ludgergoeminne** [comment]
Hi Andrew

To reload existing data, you should select "Load existing models" in the Quantification tab.
Then you are able to upload your "model file".
Don't forget to specify the "Output location" in the Input tab.

If you also want to see the effects of preprocessing, you should also upload your peptides and annotation file in the Input tab.

Let me know if this works!

Best regards

Ludger

**Comment by andrewjmc** [comment]
Duh! Seems very obvious now. I was looking for something on page 1, or a parameter when opening it.

Really impressed so far!

Thanks,

Andrew

**Comment by ludgergoeminne** [comment]
Thanks, Andrew! :)
Let me know if you have any further questions!
