### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Alex-Bayes** [statOmics/MSqRob#81]
Could not install MSqRob using a Mac (OX10.15.4) via Rstudio.

After trying this into RStudio Console:
install.packages("devtools")
library(devtools)

I get the following:

*****
> install.packages("devtools")
also installing the dependencies ‘BH’, ‘sys’, ‘ini’, ‘backports’, ‘ps’, ‘lazyeval’, ‘later’, ‘askpass’, ‘highr’, ‘markdown’, ‘xfun’, ‘clipr’, ‘clisymbols’, ‘curl’, ‘fs’, ‘gh’, ‘purrr’, ‘rprojroot’, ‘whisker’, ‘yaml’, ‘processx’, ‘R6’, ‘assertthat’, ‘fansi’, ‘rex’, ‘htmltools’, ‘htmlwidgets’, ‘magrittr’, ‘crosstalk’, ‘promises’, ‘mime’, ‘openssl’, ‘prettyunits’, ‘xopen’, ‘brew’, ‘commonmark’, ‘knitr’, ‘Rcpp’, ‘stringi’, ‘stringr’, ‘xml2’, ‘evaluate’, ‘praise’, ‘usethis’, ‘callr’, ‘cli’, ‘covr’, ‘crayon’, ‘desc’, ‘digest’, ‘DT’, ‘ellipsis’, ‘glue’, ‘git2r’, ‘httr’, ‘jsonlite’, ‘memoise’, ‘pkgbuild’, ‘pkgload’, ‘rcmdcheck’, ‘remotes’, ‘rlang’, ‘roxygen2’, ‘rstudioapi’, ‘rversions’, ‘sessioninfo’, ‘testthat’, ‘withr’
  There are binary versions available but the source versions are later:
          binary source needs_compilation
backports  1.1.5  1.1.6              TRUE
fs         1.4.0  1.4.1              TRUE
glue       1.3.2  1.4.0              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) library(devtools)
**Error in install.packages : Unrecognized response “library(devtools)”**
****
Including this last error message.

I did anyway move on with the process as outlined in GitHub MSqRob main page.
Finally i get the following messages at the end of the process.

> devtools::install_github("statOmics/MSqRob@MSqRob0.7.6")
**Error in loadNamespace(name) : there is no package called ‘devtools’**
> library(MSqRob)
**Error in library(MSqRob) : there is no package called ‘MSqRob’**

Can you help me?

best

**Comment by ludgergoeminne** [comment]
Dear Alex

It seems like the `devtools` package was simply not installed on your system.
Did you choose "Yes" when the `Do you want to install from sources the packages which need compilation? (Yes/no/cancel)` question was prompted?

I looked a bit around on the internet and it seems that the `Rccp` package is necessary when you want to install `devtools`: https://community.rstudio.com/t/cannot-install-devtools-for-r-version-3-6-1/41362.

Can you try:
1. Redo everything, but pick "yes" when asked if you want to compile the packages from source.
2. First run this: `install.packages("Rcpp", dependencies = TRUE)`, then rerun everything else.

Tell me if (1) or (2) solved your problem. Please first try (1), if that doesn't work and (2) does work, I will include this in the installation instructions.

Best regards

Ludger

**Comment by Alex-Bayes** [comment]
Dear Ludger,

Many thanks for your prompt reply.

Let me put you into context. I had used RStudio 2-3 times years ago. i did thus downloaded it just yesterday in the iMac that I am currently using. After mailing you I did try a few  things and i did install devtools using Studio. To accomplish the I had to install several other packages as well, fs, glue, usethis and many be 1 or 2 more. I do not recall having to install Rccp, sorry. But this is currently in my list of packages. To my surprise the installation of all this packages only worked when I actually choose "No" to the question:

Do you want to install from sources the packages which need compilation? (Yes/no/cancel)

Which, was a bit surprising to me, but as I told you I am not used to work with R/Rstudio. It is a bit of a blackbox to me. What I am supposed to answer here Yes or No?

Finally I could (I think) successfully install MSqRob. At least I did not get any error message after calling this:

>devtools::install_github("statOmics/MSqRob@MSqRob0.7.6")
>library(MSqRob)

But I have not yet tried it, I was readying your tutorial paper (JoProt; 2017)


Incedientally, we do not use MaxQuant instead we use Progenesi to get quantitative data from our MS data. Will this be a big issue in order to use your software? I will try to generate a peptides.txt file manually from our peptide information that is organized in there same way MaxQuant generates this peptides.txt file. Would that be easy?

Thanks for your help again.
Cheers,
àlex


Àlex Bayés, Ph.D.
Group Leader
Molecular Physiology of the Synapse Laboratory
LAB WEB: www.molecular-synapse.org<http://www.molecular-synapse.org>
Synaptic Role in Cognitive Disabilities Network: http://www.syncogdis.org

IIB Sant Pau
C/Sant Quintí, 77-79
08041 Barcelona
Spain
Tel:+34 93 553 7906
________________________________
De: Ludger Goeminne [notifications@github.com]
Enviat el: dijous, 9 / abril / 2020 10:30
Per a: statOmics/MSqRob
A/c: Alex Bayes Puig; Author
Tema: Re: [statOmics/MSqRob] Installation issue (#81)


Dear Alex

It seems like the devtools package was simply not installed on your system.
Did you choose "Yes" when the Do you want to install from sources the packages which need compilation? (Yes/no/cancel) question was prompted?

I looked a bit around on the internet and it seems that the Rccp package is necessary when you want to install devtools: https://community.rstudio.com/t/cannot-install-devtools-for-r-version-3-6-1/41362.

Can you try:

  1.  Redo everything, but pick "yes" when asked if you want to compile the packages from source.
  2.  First run this: install.packages("Rcpp", dependencies = TRUE), then rerun everything else.

Tell me if (1) or (2) solved your problem. Please first try (1), if that doesn't work and (2) does work, I will include this in the installation instructions.

Best regards

Ludger

**Comment by ludgergoeminne** [comment]
Dear Alex

The question "Do you want to install from sources the packages which need compilation?" refers to some packages that have newer versions, but which have not been compiled yet. If you choose yes, your computer will try to compile them for you. If you pick no, he will take the latest version that has already been compiled. I suggested to pick "yes" because I thought that maybe otherwise some essential packages would be missing, but if that is not the case, it is perfectly fine.

The Shiny app readily accepts Progenesis files as input, so it shouldn't even be necessary to try to convert your files.

Cheers

Ludger

**Comment by Alex-Bayes** [comment]
Hi,

Thanks, the shiny app does pop up now, so thing look good. I also saw the option to upload progenies files (peptide files I presume, no?). i though your software only worked with MaxQuant. Sorry.

Cheers,
àlex

Àlex Bayés, Ph.D.
Group Leader
Molecular Physiology of the Synapse Laboratory
LAB WEB: www.molecular-synapse.org<http://www.molecular-synapse.org>
Synaptic Role in Cognitive Disabilities Network: http://www.syncogdis.org

IIB Sant Pau
C/Sant Quintí, 77-79
08041 Barcelona
Spain
Tel:+34 93 553 7906
________________________________
De: Ludger Goeminne [notifications@github.com]
Enviat el: dijous, 9 / abril / 2020 17:31
Per a: statOmics/MSqRob
A/c: Alex Bayes Puig; Author
Tema: Re: [statOmics/MSqRob] Installation issue (#81)


Dear Alex

The question "Do you want to install from sources the packages which need compilation?" refers to some packages that have newer versions, but which have not been compiled yet. If you choose yes, your computer will try to compile them for you. If you pick no, he will take the latest version that has already been compiled. I suggested to pick "yes" because I thought that maybe otherwise some essential packages would be missing, but if that is not the case, it is perfectly fine.

The Shiny app readily accepts Progenesis files as input, so it shouldn't even be necessary to try to convert your files.

Cheers

Ludger

**Comment by ludgergoeminne** [comment]
You're welcome. :)

I have added Progenesis optionsome time ago because quite a lot of users were asking for it.
I will close this issue for now but don't hesitate to contact me further if you would run into any kind of trouble.

Good luck with your analysis!

**Comment by Alex-Bayes** [comment]
Dear Ludger,

I want a try your software with our samples. I think now I am familiarized enough with MSqRob.

There might be an issue though. In our experimental set up we first runed our samples through and SDS-PAGE gel and cut 5 bands from each lane. We did analyze each band from all samples together and I thus have one file of peptide info for each band; i.e. I do have 5 peptides files, not one.

We do not know how to generate one single peptides file from progenesis. This is something i will now ask to the prognosis helpdesk. Yet, will this be an issue? Can I upload 5 peptide files? How do I deal with that ? Or is there an easy way to collapse these 5 files?

thanks in advanced for your help.
Cheers,
àlex

________________________________


De: Ludger Goeminne [notifications@github.com]
Enviat el: dijous, 9 / abril / 2020 20:30
Per a: statOmics/MSqRob
A/c: Alex Bayes Puig; Author
Tema: Re: [statOmics/MSqRob] Installation issue (#81)


Closed #81<https://github.com/statOmics/MSqRob/issues/81>.

**Comment by Alex-Bayes** [comment]
Dear Ludger,

i wonder if you could provide further assistance to us?

I also send a new help request through GitHub

Look forward your help

cheers
àlex



Àlex Bayés, Ph.D.
Group Leader
Molecular Physiology of the Synapse Laboratory
LAB WEB: www.molecular-synapse.org<http://www.molecular-synapse.org>
Synaptic Role in Cognitive Disabilities Network: http://www.syncogdis.org

IIB Sant Pau
C/Sant Quintí, 77-79
08041 Barcelona
Spain
Tel:+34 93 553 7906
________________________________
De: Alex Bayes Puig
Enviat el: dissabte, 11 / abril / 2020 15:04
Per a: statOmics/MSqRob; statOmics/MSqRob
A/c: Author
Tema: RE: [statOmics/MSqRob] Installation issue (#81)

Dear Ludger,

I want a try your software with our samples. I think now I am familiarized enough with MSqRob.

There might be an issue though. In our experimental set up we first runed our samples through and SDS-PAGE gel and cut 5 bands from each lane. We did analyze each band from all samples together and I thus have one file of peptide info for each band; i.e. I do have 5 peptides files, not one.

We do not know how to generate one single peptides file from progenesis. This is something i will now ask to the prognosis helpdesk. Yet, will this be an issue? Can I upload 5 peptide files? How do I deal with that ? Or is there an easy way to collapse these 5 files?

thanks in advanced for your help.
Cheers,
àlex

________________________________


De: Ludger Goeminne [notifications@github.com]
Enviat el: dijous, 9 / abril / 2020 20:30
Per a: statOmics/MSqRob
A/c: Alex Bayes Puig; Author
Tema: Re: [statOmics/MSqRob] Installation issue (#81)


Closed #81<https://github.com/statOmics/MSqRob/issues/81>.
