### ISSUE TITLE
Problems with Shiny app

### ISSUE THREAD

**Issue by MatthewThe** [statOmics/MSqRob#91]
Installation of MSqRob on Ubuntu 18.04 with R3.6.3 went largely without problems (just had to install `sudo apt-get install libnetcdf-dev` to allow installation of the `ncdf4` package).

However, when trying to run the shiny app, I run into the following error.
```
> library(MSqRob)
> shiny::runApp(system.file("App-MSqRob", package="MSqRob"))

...

Warning: Error in get: object '%AND%' not found
  92: get
  91: :::
  88: fileInput [utilities.R#265]
Warning: Error in get: object '%AND%' not found
  92: get
  91: :::
  88: fileInput [utilities.R#265]
```
Which leads to this part of the code:
https://github.com/statOmics/MSqRob/blob/2b55f0798134abdaae8a89a18d9ea178a4453a4f/inst/App-MSqRob/utilities.R#L267
The shiny app's webpage is empty, except for the error message: 
```
An error has occurred!
object '%AND%' not found
```

A colleague had the exact same problem when running the stand-alone Windows package, as well as an installation of MSqRob on MacOS with R4.0.

I tried to google this shiny:::%AND% operator, but apparently the percentage signs are not search engine friendly.

**Comment by McKayME** [comment]
Matthew,

I also was frustrated by the same error and finally figured out a solution. Although I am not sure if I had the ideal approach since there still appears to be errors and I have not tested it, the web app appears to be error free. What I did was install previous versions of R (4.0.0), Bioc (3.11), mzR (2.22.0), and ProtGenerics (1.20.0) so that they were compatible with when the MSqRob app was developed and restarted R.

Best of luck.
Mike

**Comment by ludgergoeminne** [comment]
Dear Matthew and McKayME

Thank you for bringing this to my attention.
Apparently the shiny:::`%AND%` function was removed from the shiny package while MSqRob was depending on it.
I have re-introduced this function, everything should now work again.
Please try reinstalling MSqRob via

`devtools::install_github("statOmics/MSqRob@MSqRob0.7.7")`

On my side, it seems like this fixes everything with the newest versions of R and the packages.
Let me know if this works for you.
I am closing this issue for now.

Cheers

Ludger

**Comment by MatthewThe** [comment]
Hi Ludger,

Thanks a lot, that did the trick!

-Matthew
